default_install_hook_types: [pre-commit, commit-msg]

repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.252'
    hooks:
      - id: ruff
        stages: [commit, push, manual]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        name: black
        args: [--config=pyproject.toml]
        stages: [commit, push, manual]

  - repo: https://github.com/srstevenson/nb-clean
    rev: "2.4.0"
    hooks:
      - id: nb-clean
        stages: [commit, push]

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        name: 'detect-secrets'
        stages: [commit, push]

  - repo: local
    hooks:
      - id: validate-commit-msg
        name: validate-commit-msg
        language: pygrep
        # PR name example:
        # "feat: Add a new feature"
        # Do not forget the uppercase after the colon
        entry: ^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(!?)(:)\s{1}[A-Z][\w,\W,:]*$
        stages: [commit-msg]
        args: [--multiline, --negate]
